import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // Ensure static data generated by pipeline is accessible
  output: undefined,
};

export default nextConfig;
